### ISSUE TITLE
vagrant up centos7-katello-devel failing - rake db:seed returned 1 instead of one of [0]

### ISSUE THREAD

**Issue by jeffmcutter** [theforeman/forklift#1022]
I'm not having much luck trying to debug a failed vagrant up centos7-katello-devel.  I tried a vagrant up centos7-foreman-nightly and that works successfully.  At one point I was thinking it was a name resolution issue, but I noted the fqdn specified with 3 parts in the /etc/hosts file as centos7-katello-devel.jcutter-fedora.example.com and I'm thinking that should do the trick.

First error I see is just below, but many warnings before that.

[ERROR 2019-09-24T21:53:58 verbose]  'scl enable rh-ruby25 'bundle exec rake db:seed'' returned 1 instead of one of [0]

Full output here:

https://gist.github.com/jeffmcutter/4ad3451204367b9ad87bdc158aa14da9

Thanks,
-Jeff

**Comment by ekohl** [comment]
This is a known issue in the current candlepin version we ship (https://community.theforeman.org/t/candlepin-crashing-permanently-server-broke-connection-post-candlepin-owners-default-organization-uebercert/14841). We're updating it but the fix hasn't propagated yet.

**Comment by jeffmcutter** [comment]
It's working for me now.  Thanks!
