### ISSUE TITLE
vagrant up errors

### ISSUE THREAD

**Issue by jschuler** [theforeman/forklift#1132]
When i launch `vagrant up centos7-katello-devel` or with box `centos7-luna-devel` i am seeing errors about `Failed to ensure rh-postgresql12-postgresql-server, rh-redis5-redis, pulpcore-selinux are installed`. 

I am on RHEL 8.

Any idea what I could do to fix this?

More from the log:
https://pastebin.com/U6nfS76d

**Comment by ehelms** [comment]
We do not currently support EL8. Please try with EL7.

**Comment by ekohl** [comment]
@jschuler did you mean RHEL 8 as the host OS? If so, it looks like the repositories on the guest haven't been set up properly.

**Comment by jschuler** [comment]
@ekohl @ehelms yes my host is RHEL 8. I just tried it also from a host with Fedora 31 and from macosx mojave and am getting the same errors for boxes `centos7-katello-devel` and `centos7-luna-devel`.

```
➜  forklift git:(master) vagrant --version
Vagrant 2.2.6
➜  forklift git:(master) ansible --version
ansible 2.9.5
```

Only `centos7-katello-devel-stable` has come up without issue so far.

**Comment by ekohl** [comment]
> We do not currently support EL8. Please try with EL7.

This isn't actually true for hosts. We don't care about the host OS, as long as it runs vagrant.

That said, we've had broken nightlies for some time. Recently they were fixed. Would you mind trying it again?
