### ISSUE TITLE
Candlepin issue

### ISSUE THREAD

**Issue by ofedoren** [theforeman/forklift#1157]
On the latest (master, 30.04.2020) branch I'm encountering the following error:
```
[ERROR 2020-04-30T12:56:11 verbose]  /Stage[main]/Candlepin::Artemis/Selinux::Boolean[candlepin_can_bind_activemq_port]/Selboolean[candlepin_can_bind_activemq_port]: Could not evaluate: Execution of '/usr/sbin/getsebool candlepin_can_bind_activemq_port' returned 255: Error getting active value for candlepin_can_bind_activemq_port
```

Maybe it's related to https://github.com/theforeman/puppet-candlepin/pull/143.

Any advices?

**Comment by ekohl** [comment]
I think that might be related to long term red status of https://ci.theforeman.org/job/katello-nightly-rpm-pipeline/ which means the staging version isn't promoting. The [staging](http://koji.katello.org/releases/yum/katello-nightly/candlepin/el7/x86_64/) version should work.

**Comment by evgeni** [comment]
This should be fixed by now. Please re-open if not.
