### ISSUE TITLE
hammer devel server needs to be fqdn, we should add a comment

### ISSUE THREAD

**Issue by chris1984** [theforeman/forklift#1428]
https://github.com/theforeman/forklift/blob/master/vagrant/boxes.d/99-local.yaml.example#L45

If you put in the box name of the katello-server it will not connect and configure correctly. 

This issue serves too add a comment in that file so users know to use the full fqdn of their katello-server.

**Comment by chris1984** [comment]
That works, I just filed an issue. I didn't know if you wanted me to make a PR. I can if you are not going to.

**Comment by ekohl** [comment]
Please do open a PR.
