### ISSUE TITLE
Update Forklift to Alma

### ISSUE THREAD

**Issue by ehelms** [theforeman/forklift#1824]
- [x] Devel boxes
- [x] Remove CentOS 8 Stream boxes
- [x] Update smoker box to use CS9

**Comment by ekohl** [comment]
https://github.com/theforeman/forklift/pull/1820

**Comment by archanaserver** [comment]
- [ ] https://github.com/theforeman/forklift/pull/1832
- [ ] https://github.com/theforeman/forklift/pull/1826

**Comment by archanaserver** [comment]
We can close this issue now and mark all tasks completed (I don't have permission to do so).
