### ISSUE TITLE
Add support for bridged public network with DDNS

### ISSUE THREAD

**Issue by akofink** [theforeman/forklift#267]
Here's my repetitive process on some boxes:
1. `vagrant up` a box
2. open virtual machine manager
3. add another network interface through a bridge on the host
4. restart the guest
5. ensure the default route uses the public interface rather than the NAT
6. install/configure/enable ddns

I hope to use some nights and weekends to automate this in an ansible role. This setup allows working from one computer and accessing virtual machines running on a separate host without the need for SSH/SOCKS proxy setup and has the added benefit of allowing full port access rather than specifically forwarded ports.

**Comment by pronix** [comment]
is it not possible by vagrant-libvirt ?

**Comment by akofink** [comment]
@pronix I haven't been able to get the bridge working from boxes.yaml and still have the local NAT for vagrant to access. It is supposed to be supported - maybe the vagrantfile needs a bit of tweaking.

**Comment by akofink** [comment]
Nope
