### ISSUE TITLE
Re-organizing Directory Structure

### ISSUE THREAD

**Issue by ehelms** [theforeman/forklift#367]
Taking discussion from (https://github.com/Katello/forklift/pull/349#issuecomment-274358709) to have it be more pointed:

From @ekohl:
> I wouldn't mind if this lived in this repo, but we already have quite a few ways this repo can be used and we need to cut down on it and focus the documentation. As someone new to the repo it's hard to figure out what you can and can't do with it. Before we add more, we need to simplify it first. A few steps that I'd think of:

> # Split the top directory into subdirs

> Some candidates I see

> * bats
> * vagrant
> * openshift
> * docker

> # Remove deprecated things

> * Nuke setup.rb

From @ehelms:

> That sounds reasonable as a first good step to re-organize the top level (unless you think it should be part of this change only). The top level docker repository I don't know if anyone outside of myself even uses at this point. There is also a docker folder inside this PR, where in theory generic docker build directories are living. They could perhaps be moved to the top to help emphasize keeping them multi-use; I had put them there originally cause I was having to do some hacks to get them to work inside openshift.

> I am all for nuking setup.rb. I think the biggest hold back of it is the use in bats and thus the use in our CI system.

From @ekohl:

>> That sounds reasonable as a first good step to re-organize the top level (unless you think it should be part of this change only).
>No, I'd prefer to get that done first and then get this merged.

>>The top level docker repository I don't know if anyone outside of myself even uses at this point.
That's a big problem with this repo IMHO. We have a lot of possibilities and they should be maintained. >I'd like to go to a situation where each top level directory can be used independently.

>>There is also a docker folder inside this PR, where in theory generic docker build directories are living. They could perhaps be moved to the top to help emphasize keeping them multi-use; I had put them there originally cause I was having to do some hacks to get them to work inside openshift.
>That's fine, until they are generic they should live inside openshift.

>>I am all for nuking setup.rb. I think the biggest hold back of it is the use in bats and thus the use in our CI system.
>Agreed. Which is why I think we should get #331 merged and look at migrating the CI system.

**Comment by ehelms** [comment]
Based on this discussion, to help us out with transitioning, I was thinking we should maybe introduce the following:

 * proper versioning of this repository
 * branch a "stable" branch point to allow us to modify master more quickly
   - pros:
     ## allows us to move quicker and break less developers and workflows
     ## can do staged update to CI system
   - cons:
     ## longer time between changes being tested by CI or users

**Comment by ekohl** [comment]
Note: this is all thinking aloud.

I'm not sure we're ready for versioning. I'm also wondering what releases you'd create from this given we have multiple goals:

* Vagrant setup aims to support everything: 1.11/3.0 to nightly/nightly
* Openshift is still in development
* Docker is more focussed on utils that are independent of Foreman releases

That means following the Foreman release cycle might not make much sense though I could see a stable-1.11, stable-1.12 + develop (like community-templates does). Then you can drop workarounds in develop while still running CI tests against older versions. But is that something we already need?

**Comment by ehelms** [comment]
Fair point. My main goal was just to reduce any potential developer churn as we made changes.

**Comment by ekohl** [comment]
I think that's hard to avoid. Maybe we could restructure as part of the move from gh/Katello to gh/theforeman in order to be better prepared for the future use cases of the repository.

**Comment by ehelms** [comment]
Looking at the current structure and files we have, I think removing `setup.rb` first would make moving directories around easier as it would eliminate some code. I'm looking into this.

**Comment by ekohl** [comment]
I agree that removing setup.rb is the first move. If there's anything I can do to help, please say so.

**Comment by ehelms** [comment]
I am working on some updated bats based on Ansible and hope ot have a PR for review today. In the meantime, we'll need: https://github.com/theforeman/foreman-infra/pull/273

**Comment by ehelms** [comment]
Removal of `setup.rb` from this repo: https://github.com/Katello/forklift/pull/369

**Comment by ehelms** [comment]
Updates are also needed to our systest for Katello: https://github.com/theforeman/foreman-infra/pull/275

**Comment by ehelms** [comment]
Implementing discussion from this here -- https://github.com/Katello/forklift/pull/379
