### ISSUE TITLE
Pipeline capsule bats test fails

### ISSUE THREAD

**Issue by daviddavis** [theforeman/forklift#407]
Running this:

```
ansible-playbook pipelines/pipeline_katello_nightly.yml -e "forklift_state=up"
```

I get this error:

```
TASK [bats : Clone bats] *******************************************************
Tuesday 21 February 2017  13:15:19 -0500 (0:00:00.331)       0:22:03.066 ****** 
fatal: [pipeline-proxy-nightly-centos7]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find required executable git"}
```

SSHing in the box and trying to use git seems to confirm this:

```
$ git
-bash: git: command not found
```

Looks like we need to `yum install git` on the capsule VM.

**Comment by ekohl** [comment]
I ran into the same issue, fix is in https://github.com/theforeman/forklift/pull/405 as https://github.com/theforeman/forklift/pull/405/commits/670144446f094a0eadc382083ad4cd7e16ab621c

**Comment by daviddavis** [comment]
Ah, good deal.
