### ISSUE TITLE
Add option for rsync-ing local git repos for development boxes

### ISSUE THREAD

**Issue by ShimShtein** [theforeman/forklift#421]
I would like to make some local changes (on hypervisor's filesystem) and test them from centos7-devel box. It would be nice, if foreman and katello folders were synced between the hypervisor and the box. Of course the paths should be configurable, just as the username is right now.

**Comment by ehelms** [comment]
I thought this was do-able already. @jlsherrill or @waldenraines or @thomasmckay do this with development boxes if I recall correctly. Perhaps they can share their setup details.

**Comment by thomasmckay** [comment]
I only use the config files from the forklift box then symlink them into an sshfs mounted local source. This way I can edit locally and the changes are immediate in the VM.

**Comment by bastilian** [comment]
I've implemented syncing folders set in `boxes.yml` into the vm like this:

```
---
centos7-devel:
  ...
  synced:
    - <%= "#{ENV['HOME']}/RedHat/Foreman/Repos/foreman" %>
    - <%= "#{ENV['HOME']}/RedHat/Foreman/Repos/in_forklift/katello" %>
 ...
```

If configured it to use `nfs` rather than `rsync`, since it was rather slow.
I'll prepare a PR with the changes, now that #426 is merged.
