### ISSUE TITLE
Update documentation with recently added features

### ISSUE THREAD

**Issue by bastilian** [theforeman/forklift#443]
There are a few changes that are not mentioned yet in the documentation:

- Provider specific options: #442 
- Synced Folders: #430
- ERB in Yaml (included in Synced Folders)

**Comment by evgeni** [comment]
* Running bats from different repositories/branches: #464

**Comment by evgeni** [comment]
#442 did include changes to README.md, do you think those are not sufficient?

**Comment by ehelms** [comment]
Closing as I think the requested documentation is covered. Please open a new issue if you find more missing docs.
