### ISSUE TITLE
provisioning of development box does not work

### ISSUE THREAD

**Issue by mdellweg** [theforeman/forklift#493]
I tried to `vagrant up` the provisioning box `centos7-devel` as described in the README.
It fails complaining about the order parameters in `/usr/share/katello-installer-base/modules/katello_devel/manifests/database.pp` that should be numbers instead of strings.
Changing `'00[123]'` to `[123]` in the pg_hba_rules manually seems to fix that problem for now.
But another `vagrant provision` fails with ` 'install_rvm.sh' returned 1 instead of one of [0]`.
The latter seems to be a problem with rvm and can be circumvented by putting `grep -v "__rvm_print_headline"` between download and execution of the rvm script in `/usr/share/katello-installer-base/modules/katello_devel/templates/install_rvm.sh.erb`.
Can anyone fix this?

**Comment by ekohl** [comment]
https://github.com/Katello/puppet-katello_devel/pull/115 fixes this but nightlies are blocked. If you provision with ```foreman_installer_module_prs``` set to ```katello/katello_devel/115``` either through ```ansible-playbook -e``` or ```boxes.yaml``` then it should work.

**Comment by mdellweg** [comment]
Thanks! The second one seems to be a problem on the rvm side.
Feel free to close this, when Katello/puppet-katello_devel#115 hits nightly.

**Comment by ekohl** [comment]
Given we have new nightlies this can be closed.
