### ISSUE TITLE
Switch Candlepin to use cpdb instead of liquibase

### ISSUE THREAD

**Issue by ehelms** [theforeman/forklift#498]

**Comment by sean797** [comment]
@ehelms I think this can be closed https://github.com/theforeman/puppet-candlepin/commit/51ca40909f7ae82bf06f0571df673397daa56201 🎉

**Comment by ekohl** [comment]
I agree. Yay

**Comment by ekohl** [comment]
I now see it's forklift and about containers so this still needs to happen in https://github.com/theforeman/forklift/blob/3538c2e2a60cbb89f67e0db01e28a26bc85326af/containers/roles/candlepin/files/entrypoint.sh#L9-L17
