### ISSUE TITLE
Puppet 5.4.0 requirements error

### ISSUE THREAD

**Issue by lhellebr** [theforeman/forklift#633]
In nightly installation scenarios (using vagrant), the installer fails with:

```
Puppet 5.4.0 does not meet requirements for thias-squid3 (>=2.7.20 <5.0.0)
Cannot continue due to incompatible version of Puppet. Use --skip-puppet-version-check to disable this check.
```

Using the mentioned argument causes installation to succeed. That is, however, just a workaround.

**Comment by ekohl** [comment]
This is also an issue in Katello 3.6 so it needs a fix there as well. I've been meaning to get to it, but haven't had time.

**Comment by ekohl** [comment]
Currently we have a workaround in our installer to use a fork that is marked compatible. This should fix the issue within forklift. https://projects.theforeman.org/issues/22691 tracks the real issue.
