### ISSUE TITLE
centos-katello -... vagrant boxes fail to provision

### ISSUE THREAD

**Issue by MarkusTeufelberger** [theforeman/forklift#657]
centos7-katello-3.6 fails because of https://projects.theforeman.org/issues/22691

centos7-katello-nightly fails because https://github.com/Katello/katello-installer/blob/master/checks/lang.rb is triggered (`LANG` is set to `C` in the centos7 box apparently).

**Comment by ekohl** [comment]
> centos7-katello-3.6 fails because of https://projects.theforeman.org/issues/22691

We already cherry picked the fix (https://github.com/Katello/katello-installer/commit/c06d5176a8ab9c242daa3f2d55824f0c695b1d00) but it's waiting on the RC2 build.

> centos7-katello-nightly fails because https://github.com/Katello/katello-installer/blob/master/checks/lang.rb is triggered (`LANG` is set to `C` in the centos7 box apparently).

I have seen the same issue because my ```LANG``` is ```nl_NL.UTF-8``` but the boxes don't have that lang so it falls back to ```C```

**Comment by MarkusTeufelberger** [comment]
A quick and dirty fix is to add `ENV["LC_ALL"] = "en_US.UTF-8"` somewhere in `Vagrantfile`.

**Comment by ekohl** [comment]
I have considered some similar fix and it'd simplify my life as well. Can you confirm you're using another LANG as well?

**Comment by MarkusTeufelberger** [comment]
The issue is what environment variables are set (or not set) inside the virtual machine (I use the Virtual Box provider), I'm not sure how this might fix an issue with other ways to use Vagrant. It is just a single line though, so it should be easy to try out.
