### ISSUE TITLE
Install NPM in devel instances

### ISSUE THREAD

**Issue by pgagne** [theforeman/forklift#663]
Every Time I need to `vagrant up` a devel instance you need to do:

```
vagrant ssh centos7-devel
yum install npm
cd foreman
npm install
```
In order to get the WebUI to work. Forklift should do this automatically.

**Comment by stbenjam** [comment]
Shouldn't be needed anymore, if you have the latest katello_devel it will set up webpack for you because of https://github.com/theforeman/puppet-katello_devel/pull/96

I think maybe it's just not in any released package yet, do you know @ekohl ?

**Comment by ekohl** [comment]
@stbenjam I'm also surpised. This should be fixed and also in current packages.

@pgagne are you sure you have the latest packages installed?

**Comment by pgagne** [comment]
@ehelms @jturel thoughts here. Why did I have to do `npm install` to get the webui working?

**Comment by jturel** [comment]
@pgagne You were having some sort of issue with 'foreman start' not working out of the box iirc

**Comment by ekohl** [comment]
@pgagne can you verify which commit of forklift you're using and which `katello-installer-base` version is installed? If you run vagrant provision `centos7-devel`, does it change anything?

**Comment by pgagne** [comment]
Hmm, just tried it again and this seems to not be an issue. Must of been something else i was running into. Closing for now.
