### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by rahulbajaj0509** [theforeman/forklift#678]
The current README.md files specifies - cp boxes.d/99-local.yaml.example boxes.d/99-local.yaml , but when we run this command it says 
```
cp: cannot stat 'boxes.d/99-local.yaml.example': No such file or directory
```

**Comment by ekohl** [comment]
It needs to be `vagrant/boxes.d/...`. Could you come up with a patch?

**Comment by rahulbajaj0509** [comment]
@ekohl already did :)

**Comment by ekohl** [comment]
Thanks! In this repo we don't require an issue for PRs so if you know the fix, just a PR is sufficient.
