### ISSUE TITLE
Consider using fips base box

### ISSUE THREAD

**Issue by daviddavis** [theforeman/forklift#713]
cc @amitkarsale

I've created a Vagrant setup based on https://github.com/theforeman/forklift/pull/647:

https://github.com/daviddavis/fips-box-builder

I've packaged and uploaded this to the vagrant public catalog:

https://app.vagrantup.com/daviddavis/boxes/centos7-fips

If you use this box, you'll no longer need to run the fips playbook (and deal with the restarting stuff).

Corresponding pulp PR: https://github.com/pulp/devel/pull/159

**Comment by dralley** [comment]
+1, this removes a large amount of time from the provisioning process

**Comment by ekohl** [comment]
In https://github.com/theforeman/forklift/commit/f53ba95bad1e0915a4b5d92d51e0014a9c1498bf we did add a centos7-fips box. I'd be happy to accept a PR that changes the `box` in `vagrant/boxes.d/01-builtin.yaml` for `centos7-fips`.

**Comment by dralley** [comment]
@ekohl https://github.com/theforeman/forklift/pull/734

**Comment by daviddavis** [comment]
https://github.com/theforeman/forklift/pull/734 was merged. Closing this out.
