### ISSUE TITLE
Fix workaround in project creation due to Ansible 2.6 modules

### ISSUE THREAD

**Issue by ehelms** [theforeman/forklift#770]
Revert -- https://github.com/theforeman/forklift/blob/master/containers/deploy/project/tasks/main.yml#L4

**Comment by fabianvf** [comment]
Fixed in https://github.com/ansible/ansible/pull/42132 , backported with https://github.com/ansible/ansible/pull/42525

Should be in next minor release of Ansible 2.6

**Comment by ehelms** [comment]
This work is moving repositories.
