### ISSUE TITLE
containerization playbook should finish only once all the services are operational

### ISSUE THREAD

**Issue by jhutar** [theforeman/forklift#801]
I have installed minishift VM and ran the playbook:
```
minishift start --memory 16GB --cpus 4 --disk-size 50GB --iso-url centos
oc login -u developer -p a
cd forklift/containers/
eval $(minishift oc-env)
source /root/myvenv/bin/activate   # this have `pip install openshift`
ansible-playbook foreman.yml -i does-not-exist.ini -e "ansible_python_interpreter=/root/myvenv/bin/python"
```
and when the playbook finished, I have accessed OpenShift's console and noticed most of the containers are in the "pulling" state. I have waited few mins and then noticed some of the containers and in the warning state and after some more waiting all of them were fine. Would it make sense to have the playbook block until all is ready (maybe with just some optional tag)?

**Comment by ehelms** [comment]
Maybe? But I turn this a bit on it's head with https://github.com/theforeman/forklift/pull/790 which pushes the Ansible logic into an operator running in the cluster. In my testing, I run `./test/test.rb` to query until the status API returns happy from Foreman.

**Comment by jhutar** [comment]
Ah, OK, that makes sense.
