### ISSUE TITLE
Add Docker provider support for vagrant boxes

### ISSUE THREAD

**Issue by dkliban** [theforeman/forklift#906]
I love using Forklift with Pulplift. It would be even better if a developer could provision using the Docker provider for Vagrant.

Our previous development environment was configured to provision Docker backed boxes (containers). Here[0] is an example of our old Vagrantfile. It uses a Dockerfile[1] to spin up the container. Pulp developers using Macs have been using this Vagrantfile and Dockerfile to provision their environments. Lines 57 and 58 from the Dockerfile may not be needed when provisioning on Fedora. More docs on this backend can be found here[2].

[0] https://www.vagrantup.com/docs/docker/basics.html#dockerfiles
[1] https://github.com/pulp/devel/blob/master/docker/Dockerfile
[2] https://www.vagrantup.com/docs/docker/basics.html#dockerfiles

**Comment by CodeHeeler** [comment]
Here is the old Vagrantfile https://github.com/pulp/devel/blob/master/Vagrantfile.example

**Comment by ekohl** [comment]
It probably means providing the right options according to https://www.vagrantup.com/docs/provisioning/docker.html similar to https://github.com/theforeman/forklift/blob/0e5c47900233684d97ee0fd8152ba40f1640880c/vagrant/lib/forklift/box_distributor.rb#L211-L243

**Comment by ehelms** [comment]
Will be fixed by -- https://github.com/theforeman/forklift/pull/907

**Comment by Croydon** [comment]
@dkliban What is the reason to close this issue?
